# Generated by Django 2.2 on 2019-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_student_studentprojectranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='UCFID',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='majorGPA',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='overallGPA',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
