# Generated by Django 2.2.2 on 2019-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20190613_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resumeLink',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
