# Generated by Django 2.2 on 2019-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190613_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField()),
                ('DateCreated', models.DateTimeField()),
                ('TotalStudents', models.IntegerField()),
                ('Term', models.CharField(max_length=100)),
                ('First', models.IntegerField()),
                ('Second', models.IntegerField()),
                ('Third', models.IntegerField()),
            ],
        ),
    ]
