# Generated by Django 2.2 on 2019-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100)),
                ('NumStudents', models.IntegerField()),
                ('Priority', models.IntegerField()),
                ('ScheduleID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=100)),
                ('LName', models.CharField(max_length=100)),
                ('Summer', models.IntegerField()),
                ('Fall', models.IntegerField()),
            ],
        ),
    ]
