# Generated by Django 2.2 on 2019-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_scheduleproject_schedulestudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Year',
        ),
        migrations.AddField(
            model_name='schedulestudent',
            name='ScheduleProjectID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulestudent',
            name='Spring',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schedulestudent',
            name='Fall',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='schedulestudent',
            name='Summer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
