# Generated by Django 2.2 on 2019-07-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20190702_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestudent',
            name='Rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
