# Generated by Django 2.2 on 2019-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20190720_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CanDoBoth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='CanDoBoth',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
