# Generated by Django 2.2 on 2019-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_auto_20190720_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Bootcamp',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
