# Generated by Django 2.2 on 2019-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_student_bootcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSMemebers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CMSProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('project_name', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
                ('sponsor2', models.CharField(blank=True, max_length=100)),
                ('group_size', models.IntegerField()),
                ('year', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=100)),
                ('design_doc_url', models.CharField(blank=True, max_length=100)),
                ('final_doc_url', models.CharField(blank=True, max_length=100)),
                ('presentation_url', models.CharField(blank=True, max_length=100)),
                ('conference_paper_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
