# Generated by Django 2.2 on 2019-07-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_cmsmemebers_cmsproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Term', models.CharField(max_length=100)),
                ('ScheduleVersion', models.CharField(max_length=100)),
            ],
        ),
    ]
