# Generated by Django 2.2 on 2019-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_finalschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CurrentTerm',
            field=models.CharField(default='summer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='CurrentYear',
            field=models.CharField(default='2019', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentTerm',
            field=models.CharField(default='summer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentYear',
            field=models.CharField(default='2019', max_length=4),
            preserve_default=False,
        ),
    ]
