# Generated by Django 2.2 on 2019-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_auto_20190722_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsproject',
            name='senior_design1',
            field=models.BooleanField(default=False),
        ),
    ]
