# Generated by Django 2.2 on 2019-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_cmsproject_senior_design1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsproject',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cmsproject',
            name='project_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
