# Generated by Django 2.2 on 2019-07-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20190724_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CMSMemebers',
            new_name='CMSMembers',
        ),
    ]
