# Generated by Django 2.2 on 2019-07-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_auto_20190724_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='GroupNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
