# Generated by Django 2.2 on 2019-07-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_project_groupnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedSchedulerRunVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Version', models.TextField()),
            ],
        ),
    ]
