# Generated by Django 2.2 on 2019-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_loadedschedulerrunversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='OpenQuestion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
